apiVersion: v2
name: ethos-ecm-consumer
home: https://github.com/hmcts/ecm-consumer
version: 0.2.11
description: HMCTS ECM Consumer Updates Queue Service
maintainers:
  - name: HMCTS ETHOS Team
dependencies:
  - name: java
    version: 3.7.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
