apiVersion: v2
name: ethos-ecm-consumer
home: https://github.com/hmcts/ecm-consumer
version: 0.1.7
description: HMCTS ECM Consumer Updates Queue Service
maintainers:
  - name: HMCTS ETHOS Team
    email: javier.carretero@hmcts.net
dependencies:
  - name: java
    version: 3.4.5
    repository: '@hmctspublic'
