idam_api_url = "https://idam-api.aat.platform.hmcts.net"
s2s_url = "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
ccd_data_store_api_url = "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
micro_service = "ecm_consumer"
managed_identity_object_id = "a51b95da-2853-4c1f-934c-ca3bb65ac12f"
