idam_api_url           = "https://idam-api.ithc.platform.hmcts.net"
s2s_url                = "http://rpe-service-auth-provider-ithc.service.core-compute-ithc.internal"
ccd_data_store_api_url = "http://ccd-data-store-api-ithc.service.core-compute-ithc.internal"
micro_service          = "ecm_consumer"
subscription        = "DCD-CNP-QA"
