capacity = "2"
idam_api_url = "https://idam-api.perftest.platform.hmcts.net"
s2s_url = "http://rpe-service-auth-provider-perftest.service.core-compute-perftest.internal"
ccd_data_store_api_url = "http://ccd-data-store-api-perftest.service.core-compute-perftest.internal"
micro_service = "ecm_consumer"
