capacity = "2"
idam_api_url = "https://idam-api.perftest.platform.hmcts.net"
s2s_url = "http://rpe-service-auth-provider-perftest.service.core-compute-perftest.internal"
ccd_data_store_api_url = "http://ccd-data-store-api-perftest.service.core-compute-perftest.internal"
micro_service = "ecm-consumer"
managed_identity_object_id = "95ecbc8d-eab3-41a9-aa56-b34af308c2cd"
