capacity = "2"
idam_api_url = "https://idam-api.platform.hmcts.net"
s2s_url = "http://rpe-service-auth-provider-prod.service.core-compute-prod.internal"
micro_service = "ecm-consumer"
managed_identity_object_id = "4ed764fd-4355-4904-a460-eead84caac63"
